# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='data',
        ),
    ]
