# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-12 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_article_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
