# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-17 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20161012_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stoplist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
