# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-24 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_article_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='data',
        ),
        migrations.RemoveField(
            model_name='article',
            name='file',
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
