# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-22 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_article_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('hide', models.BooleanField(default=False)),
                ('data', models.CharField(blank=True, default='', max_length=3000)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='file',
        ),
        migrations.RemoveField(
            model_name='article',
            name='hide',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='data',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
