# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-24 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20161023_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='data',
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
