# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-24 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_auto_20161024_1303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(primary_key=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(default='', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
