# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-24 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_auto_20161024_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(default='', max_length=1000, unique=True),
        ),
    ]
